---
title: "100 запитань (і відповідей) про тести та вимірювання"
author: "Брюс Б. Фрей"
date: "2025-01-25"
format:  html
toc: true
toc-title: 'Зміст'
editor: visual
---

## Розділ 1. База.

## ЗАПИТАННЯ №1 *Тож, про що 100 запитань (і відповідей) про тести та вимірювання?*

Світ соціальних досліджень, статистики та вимірювань є складним. Незважаючи на те, що в сучасному світі існує безліч підручників, курсів, онлайн-інструктажів та можливостей для навчання, якщо ми хочемо знати про все це, матеріал часто спрямований дещо вище того рівня, на якому ми хотіли б його бачити. Навіть «вступні» книги чи курси можуть бути глибшими, ніж потрібно більшості з нас. І в своєму прагненні навчити нас усього, вони часто пропускають (або, в кращому випадку, занадто швидко просуваються) базові речі. Ця книжка призначена для того, щоб відповісти на всі ваші запитання, які виникають, коли ви вперше підходите до нової теми, або щоб надати огляд тих фундаментальних понять, термінів і фактів, які ви мали б засвоїти колись давно. Отже, ця книжка для зовсім нових і не дуже.

Вимірювання у соціальних науках - це окрема наука. Вона має власні теорії, жаргон, стратегії та процедури. Запитання та відповіді, підібрані для цього видання, розроблені таким чином, щоб бути максимально зрозумілими. Ми висвітлюємо ключові речі, які Вам потрібно знати про вимірювання, так, щоб припустити, що Ви розумні, але ще не вивчили жодної з цих речей.

Унаступних розділах Ви побачите, як визначаються тести та вимірювання. Ми не говоримо про те, як виміряти висоту будівлі або вагу діаманта.Ви не отримаєте споживчих відгуків про те, який прилад краще купити. І ми не говоримо про те, як перевірити систему запалювання Вашого автомобіля або який тест на вагітність є найточнішим. Ми говоримо про мистецтво кількісної оцінки ідей та концепцій, про способи отримання числа, яке точно відображає будь-яку нефізичну, абстрактну, неспостережувану людську рису/ознаку, яку Ви хочете виміряти. Ця книжка розкриває секрети, як зробити невидиме видимим.

\
*Маєте ще запитання? Дивіться #2 та #3.*

## *ЗАПИТАННЯ №2 Що таке тест?*

Ми використовуємо слово «тест» у різних значеннях. Очікування, поки закипить каструля, на яку Ви дивитеся, може випробувати Ваше терпіння. Компанії-розробники програмного забезпечення не наважуються випускати новий продукт до того, як він пройде бета-тестування. Дослідники не знають, чи є їхні результати статистично значущими, поки не проведуть статистичний тест. Ми можемо складати тест у школі, але іноді не готуємося до нього так старанно, тому що це не тест, а просто вікторина. Якщо ми проаналізуємо використання цього слова у цих контекстах, то зможемо виявити деякі спільні риси:

-   Тести складаються з процедур.

-   Тести дають результати, які мають певне значення.

-   Рішення приймаються на основі цих результатів.

-   Часто тести мають великою проблемою для тих, хто їх проходить, оскільки вимагають певних зусиль, і щодо них можуть бути прийняті відповідальні рішення.

Ми зосередимося на тих тестах, які проводяться на людях, а не на продуктах чи лабораторних тваринах, наприклад. Виходитимемо з такого визначення:

*Тест - це організований набір процедур, запитань або завдань, який дає інтерпретовані кількісні результати, призначені для відображення рівня певної характеристики людини.* (До речі, виявляється, є ще одне наукове визначення тесту - це *крейдяна оболонка деяких безхребетних і найпростіших*. Це не те визначення, яке ми будемо використовувати у цій книзі).

У підручниках з освітніх та психологічних вимірювань тести часто відрізняють від оцінювання. Нам кажуть, що оцінювання - це процес збору та аналізу даних з конкретною метою покращення. Тести проводяться лише з метою прийняття рішення. Це може бути технічно правильним у сенсі визначення, але міркування і наука, що лежать в основі всіх цих процесів - *тестування, аналізу* і (давайте додамо) *оцінювання* - однакові. І в цій книзі ми не будемо зациклюватися на відмінностях і будемо використовувати ці слова як взаємозамінні.

*Маєте ще запитання? Дивіться #3, #8 та #9.*

## *ЗАПИТАННЯ №3 Що ж насправді є вимірюванням?*

*Вимірювання* - це присвоєння чисел для позначення кількостей, якостей, предметів та ідей. У вимірюванні присвоєне число називається *балом*, і його присвоєння ґрунтується на правилах. Вимірювання - ширше поняття, ніж *тест*. Тест - це тип вимірювання, так само як і використання компасу для того, щоб знайти шлях через океан. Досить легко виміряти якусь конкретну якість, яку можна безпосередньо спостерігати, наприклад, фізичні властивості об'єкта, і цей тип вимірювання, швидше за все, не міг би заповнити цілу книгу (наприклад, з назвою на кшталт *«Два запитання та відповіді про зважування речей»*). З іншого боку, виміряти абстрактну і невидиму природу людського розуму, такі поняття, як інтелект, знання, ставлення і особистість, складніше. Ця книга зосереджена на проблемі вимірювання цих абстрактних людських якостей.

Виявляється, що при присвоєнні балів, це значення може нести різну кількість інформації. Фахівці з вимірювання визначили чотири різні типи або/та *рівні* *вимірювання*, кожен з яких надає більше інформації та дозволяє проводити більш потужні статистичного аналізу, коли ви піднімаєтеся «вище»:

1.  **Номінальний.** Це слово означає «лише за назвою» і відноситься до найменш інформативного рівня вимірювання, де цифри використовуються лише як назви категорій. Наприклад, Ви можете збирати дані про колір волосся учнів у класі. Заносячи цю інформацію в електронну таблицю, Ви можете присвоїти цифру 7 *блондинам*, *шатенам* - 2, *рудим* - 3 і так далі. Однак, ці оцінки насправді не відображають кількості. Це просто ярлики. Оцінка 3 - це не більше, ніж оцінка 7.

2.  **Порядковий.** На цьому рівні бали вказують на певний порядок з точки зору того, «скільки» чогось є. Наприклад, у пішохідному забігу найшвидший бігун може отримати 7 балів за перше місце, наступний за швидкістю - 2 і так далі. Існує більше інформації, ніж на номінальному рівні, але відстань між оцінками з точки зору того, що вимірюється (у даному випадку швидкість), невідома. Немає сенсу усереднювати ці цифри, наприклад.

3.  **Інтервальний.** Тут цифри мають реальне кількісне значення. Вони відображають точну кількість чогось. «Інтервал» означає, що між будь-якими двома сусідніми показниками існує однакова різниця в кількості. Наприклад, шкали, що використовуються на термометрах для вимірювання температури за Цельсієм або Фаренгейтом, знаходяться на рівні інтервалів. Більшість статистичних аналізів, таких як усереднення та обчислення варіабельності, дозволені на цьому рівні вимірювання.

4.  **Відношення.** Цей рівень вимірювання є інтервальним і не допускає від'ємних значень. Для термометра, який знаходиться на інтервальному рівні, дозволені значення нижче 0. Однак 0 є довільним і не означає повної відсутності чогось. На рівні співвідношення, однак, існує справжній 0. Нижче нього немає нічого. Простий підрахунок предметів - це вимірювання на рівні відношення. Твоя тітка може мати нуль котів, але вона не може мати менше нуля котів. Цей рівень називається «відношення», до речі, тому, що використання співвідношень і пропорцій тепер має сенс. Ваша тітка може мати вдвічі більше котів, ніж її сусідка, але ми не часто говоримо про те, що сьогодні вдвічі холодніше, ніж учора.

    *Маєте ще запитання? Дивіться #2 та #62.*

## *ЗАПИТАННЯ №4 Майже всі способи, які я можу придумати, щоб виміряти щось, здаються досить простими. У чому ж полягають важливі відмінності між вимірюванням чогось на кшталт Ваги та чимось більш абстрактним, як Знання?*

**Вимірювання** в освіті та психології відрізняються від вимірювань у фізичних науках, таких як фізика та інженерія, одним важливим аспектом. Об'єкт вимірювання, річ, якій ви хочете присвоїти бал, що представляє кількість, є абстрактною і її не можна побачити. Він може навіть не існувати! Ці невидимі риси та людські характеристики, які ми, соціальні науковці, хочемо виміряти, називаються **конструктами**.

Конструкт (вимовляється як «КОН-структ») не піддається безпосередньому спостереженню. Це концептуальна, нематеріальна змінна, яку розробник тесту побудував і визначив (звідси й термін «конструкт») інтелектуально, застосовуючи теорію та дослідження. Завдання розробника тесту полягає у тому, щоб знайти способи зробити ці невидимі конструкти спостережуваними.

Типовими стратегіями для оцінки конструктів є

-   **Постановка запитань**

```         
Це найбільш традиційний спосіб з'ясувати, що відбувається у нас в голові.
```

-   **Спостереження за поведінкою**

    Ми не можемо бачити думки, але можемо бачити поведінку.

-   **Постановка завдань для виконання**

    Оцінювачі - від класних керівників до керівників робіт - роблять висновки про наші навички, здібності та особистісні риси, дивлячись на роботу, яку ми виконуємо.

Оскільки ми не можемо бачити конструкти, якість вимірювання в соціальних науках значною мірою залежить від того, наскільки добре результати тесту дійсно відображають конструкт, що нас цікавить. Ці питання валідності обговорюються в питаннях №7 і №8.

Деякі з конструктів, які є загальними цілями вимірювання і обговорюються в цій книзі, включають знання, здібності, навички, інтелект, потенційний успіх у коледжі, особистість, ставлення, депресію та алкоголізм. Бачите, наскільки ці змінні відрізняються з точки зору вимірювання від зросту, ваги, швидкості чи товщини? Мистецтво вимірювання в соціальних науках протилежне мистецтву сценічного фокусника. Замість того, щоб змусити речі зникнути, розробники тестів змушують їх з'являтися.

*Маєте ще запитання? Дивіться #8 та #17.*

## *ЗАПИТАННЯ №5 Які існують різновиди тестів і як вони використовуються?*

Тести, описані у цій книжці, призначені для того, щоб виставляти бали людям. Бали призначені для кількісної оцінки рівнів невидимих рис, які називаються *конструктами*. Всі конструкти, пов'язані з тестами, які нас цікавлять, знаходяться у свідомості людей і не можуть бути помічені безпосередньо. Вони є відображенням того, що ми відчуваємо, що ми можемо робити і що ми знаємо. Це тести освіти та психології. Існує три основні типи освітніх і психологічних заходів. Вони відрізняються за своїм призначенням, за тим, чому ми їх використовуємо, і за характером конструктів, які вони вимірюють.

Більшість освітніх тестів можна класифікувати як **тести досягнень**. Це тести, які вимірюють знання та розуміння інформації та навичок, які ми вивчаємо в школі. Формат тестів варіюється від коротких і неформальних, коли вчитель викликає учня, щоб той відповів на запитання, до досить важливих, як, наприклад, великий проміжний іспит з хімії, і до 3-годинного стандартизованого вступного тесту до коледжу, що триває дуже довго. Основні тести досягнень включають *SAT, ACT* та *Graduate Record Exam (GRE).*

Ще одне застосування тестування - вимірювання здібностей, щоб передбачити або оцінити, наскільки добре людина буде працювати в школі або на роботі. Загальна назва категорії тестів, які передбачають майбутнє, - **тести на здібності**. Безумовно, найпоширенішим типом тестів на здібності в освіті та психології є **тести інтелекту**. Тести інтелекту призначені для оцінки тих здібностей, які корелюють з успіхом у навчанні, на роботі та в самостійному житті. До основних тестів інтелекту належать *Шкала інтелекту Векслера для дітей* (WISC), т*ести когнітивних здібностей Вудкока-Джонсона*, *тест Кауфмана для дітей* (K-ABC) та *Шкала інтелекту Стенфорд-Біне*.

Третій тип тестів у світі психології, а іноді і в освіті, зазвичай називають **особистісними тестами**. Вони призначені для оцінки наших почуттів, ставлень і того, як працює наш розум. Іноді ці конструкти є чітко визначеними складними психічними захворюваннями. В інших випадках особистісні тести переслідують менш складні цілі, наприклад, визначити, як ви ставитеся до нової лінійки запечених бобів компанії. Основні тести цієї категорії, такі як *Міннесотський багатофакторний особистісний опитувальник* (MMPI), оцінюють типи і розлади особистості або використовуються для діагностики таких проблем, як депресія чи залежність від алкоголю та інших наркотиків.

В інших питаннях і відповідях у цій книзі розглядаються характеристики цих тестів, необхідні для того, щоб вони були корисними, а також те, як використовуються та інтерпретуються бали, отримані за допомогою цих вимірювань. Ці методи розробки та застосування тестів по суті однакові для всіх освітніх і психологічних тестів, незалежно від того, чи призначені вони для вимірювання успішності, оцінки інтелекту та здібностей, чи для визначення особистісних якостей і ставлення до життя.

*Маєте більше запитань? Див. #4 та #7.*

## *ЗАПИТАННЯ №6* Які є способи інтерпретації тестових балів?

Насправді є лише два способи, коли результат тесту може щось означати:

1.  Ваш результат можна інтерпретувати, порівнюючи його з результатами інших. Він вищий, нижчий чи приблизно середній порівняно з іншими людьми, які проходили той самий тест? І наскільки він вищий чи нижчий порівняно з іншими? Цей підхід, який надає значення балу, розуміючи, які бали отримують нормальні люди (якщо дозволите), називається *орієнтованим на норму*. У цьому підході важливо те, чи є оцінка вищою або нижчою за середню.
2.  Оцінку можна інтерпретувати, розуміючи, що вона безпосередньо відображає з точки зору рівня певної риси, який фрагмент знань було засвоєно, наскільки добре опановано навичку, наявність чи відсутність певного стану тощо. Цей підхід не переймається тим, як чиїсь результати порівнюються з результатами інших людей, натомість інтерпретує оцінку відповідно до певних зовнішніх критеріїв чи стандартів. За такого *критеріально-орієнтованого* підходу кожен, кого оцінюють, може отримати однаковий бал або опинитися в одній і тій самій категорії ефективності. Неважливо, чи є оцінка вищою або нижчою за середню.

Як приклад, уявіть, що Ви щойно пробігли забіг довжиною в милю проти шести інших людей. Ви пробігли милю за 4 хвилини і 36 секунд. (Я сказав, що ми вдаємо.) Цей результат у 276 секунд ((4 x 60) + 36) можна інтерпретувати двома різними способами.

Якби Ви інтерпретували свій результат, спираючись на норму, Вас би цікавило, чи були Ви прибігли першим або останнім, чи виграли забіг, і кого Ви перемогли. (Зауважте, що навіть називання забігу на милю «перегонами» узгоджується з з філософією, орієнтованою на норму).

Якби Ви інтерпретували свій час бігу з точки зору критеріїв, Вас би більше цікавило, що результат у 276 секунд говорить про Вас і Ваші здібності. Наприклад, така швидкість, швидше за все, свідчить про те, що Ви дуже здорові. Це також, ймовірно, означає, що Ви опанували вміння бігати. Результат сам по собі має значення, навіть якщо Ви не знаєте, як його набрали інші.

Вступні тести до коледжів, такі як ACT, SAT, MCAT і GRE, а іноді оцінки, які ви отримуєте в школі, виставляються та інтерпретуються на основі певних норм.

«Державні тести», такі як ті, що вимагаються в американських школах відповідно до закону “Жодної дитини поза увагою”, зазвичай є критеріальними. Вони призначені для класифікації учнів на основі їхнього рівня досягнень.

Кілька простих запитань допоможуть Вам зрозуміти, чи оцінки базуються на нормах, чи на критеріях. Чи може кожен отримати однаковий бал? Якщо так, то це критеріально-орієнтоване оцінювання. Щоб зрозуміти оцінку, чи потрібно Вам знати, як інші люди ? Якщо так, то він прив'язаний до норми.

*Маєте ще питання? Дивіться #8, #17 та #80.*

## *ЗАПИТАННЯ №7* Які бувають способи оцінити, чи є тест якісним?

Якість тесту - це, по суті, питання значення балів, які виставляються за його результатами. Існує дві основні характеристики балів, які роблять їх корисними:

-   Оцінки відображають конструкт інтересу. *Конструкт* - це невидима риса, яку ми хочемо виміряти, наприклад, знання, депресія або інтелект. Тест є «хорошим», якщо він дає результати, які безпосередньо пов'язані з фактичним рівнем або *обсягом* конструкту. **Валідність** - це характеристика тестових балів, які вимірюють те, що вони мають вимірювати.

-   Бали є узгодженими для кожної людини. Бали, отримані за результатами тесту, майже завжди використовуються для прийняття рішень або суджень про людей, тому вони повинні відображати типовий результат, який отримав би кожен учасник. Це означає, що у відповідях людей на тестові завдання та запитання має бути дуже мало випадковостей. Якщо учень пропускає запитання, на яке зазвичай дає правильну відповідь, лише тому, що повз нього проїхала галаслива вантажівка або тому, що він пропустив сніданок, це впливає на узгодженість його балів. Її результат дещо відрізняється від того, яким він мав би бути, а отже, є менш *точним*. **Надійність** - це характеристика результатів тесту тесту, які є узгодженими і точними.

Отже, є два різні способи оцінити, чи є тест хорошим, чи ні. Чи він валідний? Чи він надійний?

Дослідники хотіли б, щоб я чітко пояснив, що валідними або надійними є тестові бали, а не сам тест. Це має сенс, тому що один і той самий тест можна використовувати для різних цілей з різними людьми в різних умовах і він може демонструвати відмінні рівні валідності та надійності в різноманітних контекстах.

Валідність тесту зазвичай вважається найважливішою якістю при оцінці його значущості. Числам, отриманим за допомогою тестів, надається таке велике значення, і цим результатам покладається така велика довіра, що може стати серйозною проблемою, якщо вони не означають того, що передбачається. Уявіть собі тест на депресію, який насправді вимірює, чи висипається людина, або вимір інтелекту, який погано працює для тих, чия рідна мова не англійська. Стратегії лікування, розподіл на освітні програми, вступ до коледжу, результати досліджень, прийом на роботу - все залежить від припущення, що тести вимірюють те, що вони мають вимірювати.

Надійність також важлива для оцінки якості тесту. Зауважте, що тест може бути надійним, не будучи валідним. Надійність забезпечується доти, доки люди отримують типовий бал, який вони могли б отримати за допомогою цього інструменту, незалежно від того, чи вимірює цей інструмент те, що він має вимірювати. «Математичний» тест, який насправді вимагає високого рівня навичок читання для того, щоб добре його виконати, може бути дуже надійним, але він, ймовірно, не дуже добре працює, коли використовується для вимірювання математичних здібностей.

*Маєте ще запитання? Див. #8 і #17.*
