---
title: "100 запитань (і відповідей) про тести та вимірювання"
author: "Брюс Б. Фрей"
date: "2025-01-25"
format:  html
toc: true
toc-title: 'Зміст'
editor: visual
---

## Розділ 2. Розуміння Валідності

## ЗАПИТАННЯ №8 Що означає, що тест є валідним?

Питання №7 вводило та описувало поняття валідності. Це якість тесту, яка полягає в тому, що він вимірює те, що має вимірювати. Існує багато способів стверджувати, що результати конкретного тесту дійсно відображають те, що він має відображати.

Загалом, існує чотири типи аргументів, чотири категорії доказів, які можуть підтвердити твердження про валідність. Ви можете вважати ці категорії чотирма типами валідності, якщо хочете, хоча затяті фахівці з вимірювання вважають, що валідність є такою, і хоча можна використовувати різні стратегії для розробки різноманітних аргументів на користь висновку про валідність, насправді не існує окремих «типів». Тест або корисний за своїм призначенням, або ні. Для тих, хто любить класифікувати, можна виділити чотири основні типи ознак валідності

-   **Підтвердження валідності змісту**

Аргументи, які представляють перелік або таблицю чітко визначеної області або категорії та перевіряють, чи фактичні запитання, елементи або завдання тесту справедливо представляють ці області, є аргументами валідності змісту. Якщо тест «охоплює те, що має охоплювати», то він є змістовно валідним.

-   **Підтвердження валідності критерію**

Деякі тести розроблені з конкретною метою передбачити або оцінити результати за іншим тестом або критерієм. Валідність критерію для таких тестів можна продемонструвати, надавши докази, зазвичай статистичні, того, що результати тесту дійсно корелюють з результатами іншого показниками іншого вимірювання.

-   **Підтвердження конструктної валідності**

*Конструкт* - це термін для вимірювання тієї невидимої абстрактної якості або риси, яку тест покликаний виміряти. Це те, що має представляти результат. Отже, будь-який аргумент, який посилається на цю рису і використовує теорію, дані або статистичний аналіз, щоб продемонструвати, що існує зв'язок між балом і конструктом, можна вважати доказом конструктної валідності. Якщо це визначення звучить дуже схоже на наше загальне визначення валідності, ви маєте рацію. Ось чому багато теоретиків вимірювання вважають, що всі докази валідності це докази конструктної валідності, і не існує різних типів валідності.

-   **Підтвердження послідовної валідності**

Це найсучасніша з традиційних стратегій обґрунтування валідності тесту. Аргументація валідності виходить за рамки простого твердження, що результати тесту дійсно відображають конструкт, який нас цікавить. Вона вказує на те, що тест розроблено з певною метою, і якщо загальна мета тесту не досягається, то тест не є валідним. Іноді це називають *валідністю соціальних наслідків.* Наприклад, твердження про те, що використання протягом багатьох років певного тесту на поведінку в класі призвело до того, що непропорційно велика кількість хлопчиків була визначена як такі, що мають дефіцит уваги/гіперактивність (РДУГ), буде наслідком проблеми з валідністю.

*Маєте ще запитання? Дивіться #17, #28 та #40.*

## ЗАПИТАННЯ №9 Що таке валідність змісту, чому вона важлива і як її визначають?

*Валідність змісту* - це характеристика тесту, який складається із завдань, що об'єктивно репрезентують усі завдання, які можуть бути включені до тесту. Для стандартизованого тесту успішності, чи представляють запитання всі традиційні академічні сфери, які вважаються важливими, такі як читання, письмо та математика? Якщо тест проводиться вчителем у класі, чи кожне завдання пов'язане з важливою навчальною метою? Чи тест «охоплює те, чого навчали»? Якщо йдеться про психологічний чи особистісний тест, чи всі ключові відмінні характеристики певного розладу чи риси враховані в запитаннях?

Валідність змісту важлива, оскільки вона демонструє, що абстрактний конструкт, невидима риса або змінна, яку ми хочемо виміряти (див. Запитання № 3), була операціоналізована у розумний спосіб. Для того, щоб зробити невидиму ознаку спостережуваною, необхідно відповісти на конкретні запитання або виконати конкретні завдання. (Зрештою, освітні та психологічні вимірювання - це наука про *поведінку*). Ці питання або завдання повинні відображати належну структуру або організаційну схему, яка визначила конструкт за областями, або підобластями, або групами поведінки. Ми повинні мати чітке визначення того, як виглядає риса, коли ми її бачимо. Тест з хорошою валідністю змісту дає бали, які дозволяють нам «побачити» конструкт.

Тести з добре встановленою валідністю змісту зазвичай починаються з переліку або таблиці, в якій детально описані суттєві елементи конструкту. Цей перелік може бути розроблений професійною організацією, яка встановила стандарти знань або навичок для представників своєї професії, що практикують. Він може походити з прийнятих теорій або наукових досліджень, які визначили компоненти особистісної риси або хвороби, що мають бути включені в будь-яке валідне оцінювання. Це може бути пропозиція класного керівника, який розробив *таблицю специфікацій* щодо того, що має охоплювати підсумковий тест і яку увагу слід приділяти кожній темі.

Більшість аргументів щодо валідності зосереджені на самому тестовому балі. Натомість аргументи щодо валідності змісту зосереджені на змісті тесту, завданнях і запитаннях. Чи є запитання справедливою репрезентацією запитань, які мають бути в тесті? тесті?

*Маєте ще запитання? Див. #40 та #71.*

## ЗАПИТАННЯ №10 Що таке валідність критеріїв, чому вона важлива та як вона встановлюється?

*Критеріальна валідність* - це характеристика тесту, яка полягає в тому, що результати тесту корелюють з деякими іншими показниками. Зазвичай, фактичний коефіцієнт кореляції - статистика, яка кількісно визначає розмір і характер зв'язків між змінними (див. Запитання № 28) - використовується як доказ сили зв'язку між двома наборами балів, хоча для встановлення зв'язку можуть бути використані й інші результати досліджень. Наприклад, розробники вступного тесту до коледжу хотіли б показати, що результати їхнього тесту корелюють з успішністю в коледжі, можливо, з середнім балом після першого року навчання. Розробники загальношкільного тесту, що проводиться на початку року і має на меті передбачити результати загальнодержавних тестів з математики, які складатимуться наприкінці року, мають продемонструвати сильний зв'язок між результатами свого тесту і результатами тесту на рівні штату. Нові версії загальноприйнятих тестів, таких як особистісні тести або тести інтелекту, які хочуть запропонувати свої оцінки в якості валідних аналогів, стверджують, що результати їхніх тестів добре корелюють з результатами «золотого стандарту», який вони хочуть замінити.

Валідність критерію важливо встановити для тестів, які передбачають майбутнє або оцінюють паралельне виконання якогось іншого тесту. Ці два аспекти валідності критерію розглядаються як два окремі аргументи валідності: **прогностична валідність критерію** та **паралельна валідність критерію**.

Для встановлення валідності критерію зазвичай потрібні дослідження. Розробники тестів або ті, хто вивчає валідність тесту, формують вибірку учасників тестування і просять їх пройти обидва вимірювання або збирають дані для обох вимірювань у певний спосіб. Потім обчислюють коефіцієнт кореляції між двома наборами балів. Зазвичай, високий коефіцієнт кореляції підтверджує обґрунтованість критерію. Однак, залежно від фактичних тверджень про конструкт, що вимірюється, можна сподіватися на помірну кореляцію, низьку кореляцію або навіть на відсутність зв'язку взагалі. Наприклад, якщо я маю новий, модний спосіб визначення та оцінки інтелекту, я хотів би продемонструвати, що мій показник дещо корелює з іншими тестами інтелекту, не настільки високо, щоб припустити, що я не роблю нічого нового, але й не настільки низько, щоб припустити, що я низькою, щоб це свідчило про те, що я взагалі не вимірюю інтелект.

Валідність критерію фокусується на самому тестовому балі. Чи дійсно він відображає передбачуваний конструкт? Якщо так, то він повинен корелювати з іншими тестами, які нібито вимірюють той самий конструкт.

*Маєте ще запитання? Див. #40 та #51.*

## ЗАПИТАННЯ №11 Що таке валідність конструкції, чому вона важлива, і як вона встановлюється?

*Конструктну валідність* можна визначити двома способами, залежно від того, чи Ви налаштовані на широкий, філософський лад, чи хочете отримати більш конкретне, прикладне визначення. У широкому розумінні, згідно з думкою фахівців з вимірювання та сучасними підручниками, будь-яка валідність є конструктною. Тобто, конструктну валідність зазвичай визначають як характеристику тесту, результати якого відображають конструкт (невидиму рису), який тест має на меті виміряти. Але насправді це те саме визначення, яке ми використовуємо для *валідності* загалом. Отже, спосіб мислення, який називається *унітарним* поглядом на валідність, розглядає всі аргументи валідності як аргументи конструктної валідності і стверджує, що говорити про різні типи валідності не є корисним, або, що ще гірше, вводить в оману. Інший підхід до визначення конструктної валідності чудово справляється з категоризацією аргументів валідності на «типи», такі як *валідність змісту* і *валідність критерію.* У цій книзі ми говоримо про типи валідності і розглядаємо ті аргументи валідності, які стосуються теорії про природу конструкту або концептуального визначення конструкту, як аргументи *конструктної валідності*.

Конструктна валідність важлива для всіх типів тестів (оскільки вона є основною вимогою до всіх тестів), але вона особливо важлива для тих тестів, які призначені для вимірювання дуже абстрактних або складних змінних. Вона також особливо важлива для тестів, які вимірюють суперечливі конструкти. Наприклад, такі риси, як інтелект, депресія, залежність, аутизм, синдром дефіциту уваги та когнітивні порушення можуть бути визначені по-різному, і всі вони мають політично і соціально чутливу історію та культурно відмінні визначення. Будь-який тест, який має на меті виміряти один з цих типів конструктів, повинен мати дуже сильні та всебічні докази валідності конструкту.

Аргументи на користь валідності конструкту зазвичай будуються на поєднанні різних типів доказів. Теорія, як правило, є основою і фундаментом для аргументів на користь валідності конструкту. Результати досліджень, які показують, що бали «поводяться» так, як вони повинні, можуть бути використані для підтримки тверджень про валідність конструкта. А оскільки конструктна валідність є широким поняттям, що охоплює всю валідність, докази валідності критеріїв та валідності змісту часто використовують для аргументації валідності конструкту.

Як ви знаєте, що результат тесту дійсно відображає те, що має відображати? Дайте відповідь на це запитання, і ви встановите конструктну валідність.

*Маєте ще запитання? Див. #50 і #60.*

## ЗАПИТАННЯ №12 Що таке консеквентна валідність, чому вона важлива, і як вона встановлюється?

*Консеквентна валідність*, або валідність соціальних наслідків, стосується непередбачуваних соціальних наслідків використання тесту. Вона відповідає ширшому визначенням валідності, ніж те, яке традиційно застосовується.

Ви пам'ятаєте, що валідність, як її зазвичай визначають, - це щось на кшталт «чи вимірює тест те, що він має вимірювати». Точніше кажучи, валідність - це це *ступінь*, до якого результати тесту відображають передбачуваний конструкт. Згідно з цим загальноприйнятим розумінням терміну, непередбачувані соціальні наслідки використання тесту, хоча і є важливими, але не впливають на валідність тесту. Однак, кілька десятиліть тому офіційні стандарти вимірювання, підтримані різними зацікавленими професійними організаціями, такими як *Американська асоціація освітніх досліджень* та *Американська психологічна асоціація*, запропонували розширений погляд на валідність тестів. Американська асоціація освітніх досліджень та Американська психологічна асоціація, надали розширений погляд на валідність як на ступінь корисності тесту для в*икористання за призначенням*. І якщо тест має на меті допомогти суспільству та людям, яких тестують, то валідність має бути важливою.

Щоб з'ясувати, чи є тест валідним з точки зору наслідків, необхідно розглянути кілька різних соціальних наслідків використання тесту:

-   Які дії ініціюються після того, як особа отримує певний бал? Що відбувається вище або нижче певних високих або низьких «прохідних балів»?

-   Які внутрішні соціальні цінності імпліцитно (або експліцитно) пов'язані з використанням тесту? Як суспільство ставиться, наприклад, до високих чи низьких балів IQ або результатів SAT?

-   Чи «навішують» учням ярлики на довгі роки (а, можливо, і на все життя) і зараховують їх до категорій або шляхів, з яких неможливо вирватися, навіть якщо вони більше не будуть належати до тієї чи іншої категорії? Навіть якщо при повторному тестуванні він або вона вже не належатиме до цієї категорії?

-   Чи є технічні якості тесту (з точки зору надійності та традиційних стандартів валідності) достатньо високими? стандартів валідності) є достатньо високими, щоб використання тесту було етичним? Чи існують докази упередженого ставлення до ідентифікованих груп при використанні тесту?

-   Які правові наслідки ідентифікації або працевлаштування в результаті використання тесту? У результаті використання тесту?

*Маєте ще запитання? Див. #13 та #14.*

## ЗАПИТАННЯ №13 Що означає, що тест є упередженим?

Батьки, учні, вчителі, лікарі, пацієнти, роботодавці, претенденти на роботу, розробники тестів, дослідники - усі зацікавлені сторони у світі тестів та вимірювань - мають на увазі майже одне й те саме, коли хвилюються, що тест може бути *упередженим*. Вони мають на увазі, що тест несправедливий до певної групи.

Якщо тест має вимірювати «хороші» речі, як-от інтелект чи досягнення, то упереджений тест дає нижчі бали для членів групи. Якщо тест має вимірювати «погану» якість, наприклад, агресію або синдром дефіциту уваги, то упереджений тест дає вищі бали для цієї групи. (Упередженість також може відбуватися в напрямку, який насправді покращує показники відповідної групи, але учасники тестування зазвичай не переймаються такою упередженістю).

Упередженість проявляється у систематичній природі помилок, яких припускається тест при визначенні балів для учасників тестування з певною демографічною характеристикою, що нас цікавить. Тести, які допускають випадкові помилки, на відміну від послідовних, систематичних помилок, не вважаються упередженими. (Такі тести страждають від низької надійності, але за визначенням не є *упередженими*).

Часто існує важлива відмінність між тими, хто складає тести, і тими, хто їх розробляє, з точки зору того, які докази необхідні для висновку, що тест є упередженим. Розглянемо, наприклад, тест шкільних досягнень, який вимірює математичні здібності. Іноді виявляється, що існує розрив у результатах між чоловіками і жінками, коли чоловіки отримують дещо вищі бали на стандартизованих математичних тестах, ніж жінки. Дехто сприймає таку різницю в результатах цих тестів як доказ того, що тест є упередженим. Однак, розробники тестів зазвичай не розглядають саму лише наявність групових відмінностей як доказ упередженості тесту. Замість цього вони висувають дещо складнішу, але досить розумну вимогу. Візьміть дві великі групи чоловіків і жінок й попросіть їх усіх пройти тест. У цих великих групах груп виберіть групу чоловіків і групу жінок, які набрали приблизно однакову кількість балів у загальному тесті. Потім проаналізуйте кожне питання тесту і подивіться, наскільки добре воно прогнозує загальний результат (який вважається найкращою оцінкою здібностей). Подивіться на цей зв'язок для чоловіків, а потім для жінок. Якщо зв'язок між завданням і загальним балом відрізняється (за силою) для однієї групи порівняно з іншою, то можна зробити висновок, що це питання може бути упередженим. Окремі завдання часто визначаються як потенційно упереджені таким чином і вилучаються, щоб переконатися, що тест у цілому не є упередженим.

*Маєте ще запитання? Дивіться #14, #19 та #20.*

## ЗАПИТАННЯ №14 Як виглядають ознаки упередженості тесту?

Для науковців, які займаються вимірюваннями, *упередженість* означає, що тест систематично присвоює неправильні бали особам, які є членами певної демографічної групи, наприклад, раси, етнічної приналежності чи статі. Упередженість є особливо шкідливою, коли члени групи отримують нижчі бали, ніж вони повинні, під час оцінювання з високими ставками, таких як вступні тести до коледжів, тести інтелекту та тести на профпридатність. Використовуючи професійну мову, тест є упередженим, якщо він демонструє *диференціальну валідність*. Він є точним і справедливим для одних груп, але не для інших. Існує кілька типів доказів або аргументів, які можуть свідчити про упередженість тесту.

Докази можуть бути зосереджені на завданнях або запитаннях тесту. Якщо дві різні групи, які в інших відношеннях мають однакові здібності або знання, відрізняються в тому, чи правильно вони виконують певне завдання, це може свідчити про упередженість щодо цього завдання. Іноді зміст питань може відображати стереотипи або культурні упередження, які можуть поставити певну групу в невигідне становище. Наприклад, питання з математики, які стосуються інвестицій у взаємні фонди, можуть мати сенс лише для тих, чий сімейний дохід такий, що вони обговорюють пенсійні стратегії за обіднім столом. Ідея полягає в тому, що це питання може бути валідним для вимірювання математичних здібностей для одних, але не для інших. Це диференційна валідність.

Інший аргумент на користь наявності упередженості тесту зосереджується на базовому *конструкті* (наприклад, здібності, інтелекті, навичках, рисах особистості), який тест покликаний виміряти. Чи є цей конструкт однаковим для різних груп? Докази на користь цих аргументів зазвичай є кореляційними. Чи однаково корелюють результати цього тесту з результатами інших подібних тестів? Наприклад, якщо результати вступного тесту до коледжу (наприклад, SAT або ACT) досить добре корелюють з оцінками на першому курсі коледжу для білих студентів, але не дуже добре для студентів корінних американців, то цей тест демонструє диференційну валідність. Іноді аргумент на користь конструктивізму роблять, дивлячись на кореляції між частинами тесту. Уявіть собі тест інтелекту, який призначений для вимірювання двох різних конструктів, наприклад, таких як вербальні здібності та навички розв'язання проблем. Завдання субтесту вербальних здібностей повинні добре корелювати між собою і не дуже добре з завданнями субтесту навичок вирішення проблем. Це, ймовірно, є основною вимогою загальної валідності. Проте, що, якщо ці очікувані кореляції існують для дівчат, але не для хлопців? Це означає, що тест вимірює дещо різні конструкти для різних статей. Це диференційна валідність. І це свідчення упередженості тесту.

*Маєте ще запитання? Дивіться питання #19 та #20.*

## ЗАПИТАННЯ №15 Деякі типи доказів валідності можуть бути більш важливими для одних типів тестів, але не важливими для інших типів тестів. Яка загальна стратегія наведення аргументів на користь валідності тесту?

У цій книзі розглядаються чотири аспекти валідності (див. питання №9, №10, №11 та №12). *Валідність змісту* - це ступінь, до якого тест включає завдання, що є справедливою репрезентацією всіх завдань, які можуть бути в тесті. *Критеріальна валідність* фокусується на тому, наскільки добре результати тесту корелюють з результатами іншого тесту, який має вимірювати те саме. *Конструктна валідність* - це загальна вимога, що бали повинні відображати певний конструкт. *Наслідкова валідність* стосується того, чи наслідки для тих, хто проходить тест, незалежно від отриманих балів, є такими, як передбачалося.

Незважаючи на те, що всі типи валідності є важливими для всіх вимірювань у соціальних науках, дехто розглядає валідність як єдину концепцію, яка не має різних «типів» (див. питання №11), різні категорії тестів, як очікується, наголошуватимуть на різних аспектах валідності. Різні типи валідності обґрунтовано вважаються більш важливими залежно від мети тесту.

Тести, які призначені для вимірювання знань з добре налагодженої та організованої бази знань, такі як навчальні іспити в класі та загальнодержавні шкільні тести, повинні встановити, що їхні завдання добре представляють цю базу знань, тому важлива валідність змісту. Вступні тести до коледжів та інші заходи, які претендують на прогнозування чи оцінювання успішності в якійсь іншій сфері, повинні, як мінімум, забезпечувати докази валідності критеріїв. Тести інтелекту та інші психологічні тести, які вимірюють суб'єктивні і, можливо, суперечливо визначені риси, що випливають з комплексних теорій людської поведінки, докладають чимало зусиль, щоб обґрунтувати визначення своїх об'єктів вимірювання. Ці тести докладають значних зусиль для побудови доказів валідності. Четвертий тип аргументації валідності, послідовна валідність, є особливо важливим для вступних тестів. Результати вступних тестів використовуються для розподілу учасників тестування на певні «напрямки» або програми. Наприклад, вступні тести використовують на роботі, під час вступу до коледжу, а також у спеціальних навчальних закладах. Питання наслідків стосується того, чи отримають люди користь від такого розподілу. Валідність наслідків також стає проблемою, коли тести оцінюють на предмет упередженості. Якщо представники різних рас, етнічних груп чи статей мають більшу чи меншу ймовірність отримати різні місця роботи, то з часом це має позитивний чи негативний вплив на суспільство? негативний вплив на суспільство?

У цій таблиці наведено різні типи тестів та аспекти валідності, які можна вважати найбільш важливими для встановлення:

|   |       Зміст |      Критерії |    Конструкт |     Наслідки |
|------------------------|------------|------------|------------|------------|
|              Тести успішності |           X |  |  |  |
|         Вступні іспити до коледжу |  |           X |  |  |
|   Тести на інтелект та особистість |  |  |           X |  |
|              Вступні тести |  |  |  |           X |

*Маєте ще питання? Дивіться #7, #8 та #20.*

## ЗАПИТАННЯ №16 Мені потрібно створити тест. Як я можу переконатися, що він валідний?

Існує низка кроків, які ми можемо виконати, якщо наша мета - створити тест і вірити у його валідність, коли все сказано і зроблено. Процес починається з визначення конструкту і закінчується створенням остаточного інструменту, який можна переглядати і вдосконалювати з часом. Нижче наведено процедуру розробки валідного тесту:

1.  **Визначте конструкт або конструкти.**

    Вирішіть, що хочете виміряти. Ви сподіваєтеся виміряти ставлення для наукового дослідження? Ви класний керівник, якому потрібно оцінити, чи досягаються навчальні цілі? Вам потрібно спрогнозувати успіх у вашому громадському коледжі?

2.  **Визначте свій конструкт(и).**

    Існує два способи визначення того, що ви хочете виміряти:

    a\. Описуйте абстрактне поняття, яке ви хочете виміряти, словами, доки не отримаєте визначення на зразок словника. *Яка природа інтелекту? Якого рівня розуміння Ви бажаєте для своїх учнів? Чи є депресія тим самим, що й гнів?*

     b. Створіть план тесту. Склавши таблицю специфікацій, у якій визначено домени, піддомени, області та категорії, а також відносну вагу з точки зору кількості завдань для кожного з них, Ви знатимете, з яких частин складатиметься Ваш тест.

3.  **Розробіть запитання, елементи або завдання, які зроблять Ваш конструкт видимим.**

    Яка поведінка або тип відповідей вказуватиме на наявність абстрактної характеристики, яку Ви хочете виміряти? Як Ви можете зробити конструкт спостережуваним?

4.  **Напишіть велику кількість пунктів або завдань.**

    Створіть більший резерв, ніж ви думаєте, що вам знадобиться, щоб пізніше ви могли вибрати найвагоміші об'єкти для остаточного варіанту.

5.  **Розробіть систему оцінювання.**

    Ваш тест складається з правильних чи неправильних запитань, які можна оцінити за допомогою «1» та «0» за кожне завдання? Чи результати є більш суб'єктивними, і найбільш прийнятною буде шкала оцінювання, яка дозволяє виставляти різні бали залежно від характеру відповідей?

6.  **Протестуйте тест.**

    Роздайте Ваші завдання великій групі людей, які представляють цільову популяцію для вашого тесту і вивчіть результати.

7.  **Виберіть ті пункти, які підвищують валідність.**

    Які завдання, за статистикою, найкраще вимірюють Ваш конструкт? Чи формулювання і формат кожного завдання добре підходять для Вашої вибірки?

8.  **Створіть фінальний тест з найкращими завданнями.**

9.  **Продовжуйте збирати дані про ефективність вашого тесту.**

    Після того, як Ви закінчите «фінальну» версію свого тесту, Ви захочете покращити та переглянути його з плином часу.

    *Маєте ще запитання? Див. пункти #8, #17, #60 та #71.*
