---
title: "100 запитань (і відповідей) про тести та вимірювання"
author: "Брюс Б. Фрей"
date: "2025-01-25"
format:  html
html:
    toc-title: 'Зміст'
    editor: visual
---

# Передмова

Нас оточують цифри. У сучасному світі ми значною мірою визначаємось за результатами тестування. Для учнів і вчителів типовий шкільний день зосереджений на складанні іспитів або підготовці до них. Курсові роботи студентів коледжів дедалі частіше включають підготовку до вимірювання, тестування та оцінювання. Дослідження, особливо в соціальних науках, залежать від валідних і надійних вимірювань для перевірки гіпотез і, як виявляється, навіть для того, щоб мати шанс на отримати статистично значущі результати.

*100 Запитань (І Відповідей) Про Тести Та Вимірювання* ставить (і дає відповіді) важливі запитання про світ вимірювань у соціальних науках. Посібник призначений для студентів, які не знайомі з цими поняттями, студентів старших курсів і професіоналів, яким потрібен огляд ідей і процедур вимірювання, а також для всіх, хто зацікавлений у тому, щоб дізнатися більше про тест, який їм доведеться складати та про інтерпретацію отриманих балів.

Усі запитання (і відповіді) пронумеровані і розміщені в тому порядку, який, на нашу думку, має сенс, але Ви можете прочитати будь-яке запитання (і відповідь) з будь-якого місця в книзі, не обов'язково читаючи все, що було перед ним. Проте, якщо Ви зацікавлені в отриманні додаткової інформації, кожна відповідь закінчується пропозиціями щодо інших запитань, які стосуються суміжних тем.

100 запитань (і відповідей) згруповані в 10 категорій, щоб Ви могли швидко знайти потрібну відповідь і, можливо, випадково дізнатися про інші суміжні речі. До цих 10 розділів належать

-   База

-   Розуміння валідності

-   Розуміння надійності

-   Статистика вимірювань

-   Тести досягнень

-   Тести інтелекту

-   Особистісні тести та шкали ставлення

-   Оцінювання в класі

-   Розуміння тестових звітів

-   Опитування.

Ви помітите, що книжка невелика, а всі запитання (і відповіді) займають лише одну-дві сторінки. Це зроблено для того, щоб *«100 Запитань (І Відповідей) Про Тести Та Вимірювання»* могли слугувати зручним, стислим довідником, який можна тримати під рукою, коли виникають проблеми з вимірюванням або сумніви.

Метою було надати короткі відповіді, які представляють найважливіші концепції, процедури та інформацію. Ймовірно, ми могли б включити ще сотні запитань, але ми сподіваємося, що ви знайдете тут відповіді на свої найактуальніші питання, на які ви хотіли б отримати відповіді!но, ми могли б включити ще сотні запитань, але ми сподіваємося, що ви знайдете тут відповіді на свої найактуальніші питання, на які ви хотіли б отримати відповіді!

# Подяки

Дякуємо редакційній та виробничій команді SAGE на чолі з Вікі Найт, старшим редактором, та Нілом Салкіндом, редактором серії. Це був приємний досвід завдяки Вам і Вашим колегам. Ви всі були дуже добрі до мене.

Дякую всім рецензентам за їхній час та внесок: Гектор Б. Креспо-Буйоса, Університет Карлоса Альбісу, Сан-Хуан, Пуерто-Рико; Брюс Р. Де Фордж, Університет Меріленда, Балтимор; Шеріс Ю. Фланаган, Християнський університет Абілена; Джессіка К. Хаузер, Коледж Св. Вінсента; Наталі Джонсон-Леслі, Університет штату Арканзас; Девід Олівер Касдан, Оклендський університет; Вільям К. Куба, Університет Вільяма Пенна; Карен С. Лінструм, Північно-Західний Університет штату Оклахома; Майкл Джей Рей, Коледж в Брокпорті; і Стефані Л. Скіфрес, Університет Індіани, Пердью Університету Колумба в Індіані.

Додаткова подяка висловлюється членам виробничої групи.

# Про автора

**Брюс Б. Фрей**, доктор філософії, відзначений нагородами викладач і науковець Канзаського університету. Його наукові інтереси включають оцінювання в класі та розробку інструментів. Доктор Фрей є автором книг «Сучасне оцінювання в класі» (Modern Classroom Assessment), опублікованої видавництвом SAGE, та «Статистичні хаки» (Statistics Hacks), опублікованої видавництвом O'Reilly. Він також є співредактором Енциклопедії дослідницького дизайну SAGE. У вільний час він колекціонує комікси і особливо полюбляє історії DC 1960-х років, в яких супер-тварини повстають проти своїх господарів-супергероїв.

# Розділ 1. База.

## ЗАПИТАННЯ №1 *Тож, про що 100 запитань (і відповідей) про тести та вимірювання?*

Світ соціальних досліджень, статистики та вимірювань є складним. Незважаючи на те, що в сучасному світі існує безліч підручників, курсів, онлайн-інструктажів та можливостей для навчання, якщо ми хочемо знати про все це, матеріал часто спрямований дещо вище того рівня, на якому ми хотіли б його бачити. Навіть «вступні» книги чи курси можуть бути глибшими, ніж потрібно більшості з нас. І в своєму прагненні навчити нас усього, вони часто пропускають (або, в кращому випадку, занадто швидко просуваються) базові речі. Ця книжка призначена для того, щоб відповісти на всі ваші запитання, які виникають, коли ви вперше підходите до нової теми, або щоб надати огляд тих фундаментальних понять, термінів і фактів, які ви мали б засвоїти колись давно. Отже, ця книжка для зовсім нових і не дуже.

Вимірювання у соціальних науках - це окрема наука. Вона має власні теорії, жаргон, стратегії та процедури. Запитання та відповіді, підібрані для цього видання, розроблені таким чином, щоб бути максимально зрозумілими. Ми висвітлюємо ключові речі, які Вам потрібно знати про вимірювання, так, щоб припустити, що Ви розумні, але ще не вивчили жодної з цих речей.

Унаступних розділах Ви побачите, як визначаються тести та вимірювання. Ми не говоримо про те, як виміряти висоту будівлі або вагу діаманта.Ви не отримаєте споживчих відгуків про те, який прилад краще купити. І ми не говоримо про те, як перевірити систему запалювання Вашого автомобіля або який тест на вагітність є найточнішим. Ми говоримо про мистецтво кількісної оцінки ідей та концепцій, про способи отримання числа, яке точно відображає будь-яку нефізичну, абстрактну, неспостережувану людську рису/ознаку, яку Ви хочете виміряти. Ця книжка розкриває секрети, як зробити невидиме видимим.

\
*Маєте ще запитання? Дивіться #2 та #3.*

## *ЗАПИТАННЯ №2 Що таке тест?*

## *ЗАПИТАННЯ №3 Що ж насправді є вимірюванням?*

## ЗАПИТАННЯ №4 Майже всі способи, які я можу придумати, щоб виміряти щось, здаються досить простими. У чому ж полягають важливі відмінності між вимірюванням чогось на кшталт Ваги та чимось більш абстрактним, як Знання?
